# Spatial Interaction notes

====================================================================

## Testing of Adam Dennett Australian dataset

### First gravity model (unconstrainted + total constrained)

For $V$ (origin "emissiveness") we will use origin population (`ORIG_POP`)
For $W$ (destination "attractiveness"), we will use destination GDP per capita (`DEST_GDP_CAP`)
For $d$, we use $d^\beta$, where $d$ = `NEAR_DIST` and $\beta=-2$

`gm1` =  $V$ * $W$ * $d$

[*] Add Field (`gm1`), Float, following equation:

pow(!ORIG_POP!, 1) * pow(!DEST_GDP_CAP!, 1) * pow(!NEAR_DIST!, -2)

This produces an unconstrained output (unitless), as we have not used the k factor, which converts our model to a *total constrained* version by scaling to match the total number of flows i.e., sum of all observed flows divided by the sum of all of the other elements in the model.

[13] Using Explore Statistics, return the sum of `flow` (102228926.73000628) and `gm1` (3912.65851170132), and then calculate a new field incorporating the scale factor (`gm1_scale`)

2459831281.6548953 = model
14034836.829999987 = data

!gm1! * (102228926.73000628 / 3912.65851170132)

!gm1! * (14034836.829999987 / 2459831281.6548953)

  [!] Note: we can't do this all via Add Field, as this is a row-wise calculation
  
[14] Model evaluation

  First, check the total of `gm1_scale` matches the total flow (it does!), so our model is *total constrained*

  [!] However, the output is pretty abysmal here (R2=0, Create Chart, Sactter Plot), for example the UK - Isle of Man, which predicts based on high destination GDP * high origin population * very small distance
  
  [!] Overpredictions for small countries i.e., Hong Kong - Macau
  
  [!] Underpredicting elsewhere i.e., India-USA, Venezuela-Colombia, Bangladesh-India
  
  [!] Large flows e.g.,	MEX to USA = 2519677.52, but USA to MEX also high = 1373658.95

  [UN DATA] We're also not capturing other key events e.g., Ukraine to Germany
  
  [UN DATA] It is also not handling negative values e.g., less Kazakshtan residents living in Russia (2024 vs. 2020)
  
### Tuning parameters

If we log both sides of the equation above, we get the following:

$\mathrm{ln}T_{ij}=k+μ\mathrm{ln}V_i+α\mathrm{ln}W_j−β\mathrm{ln}d_{ij}$

This is basically a regression model! 

However, there are problems with this approach, and instead we use Poisson regression, which is better for skewed distributions (like our flow data)

[*] Visualise Statistics - Histrogram - Flow

So our Poisson regression looks like the following:

$λ_{ij}=\mathrm{exp}(k+μ\mathrm{ln}V_i+α\mathrm{ln}W_j−β\mathrm{ln}d_{ij})$

[*] First, log the independent variables using Add Field
  -> math.log(!vi1_origpop!)
  -> math.log(!wj3_destmedinc!)
  -> math.log(!NEAR_DIST! / 1000) # converting to km
  
[*] Generalized Linear Regression (GeoAnalytics Desktop Tools)
  -> Flow (dependent)
  -> Logged variables (independent)
  -> Count (Poisson)

[*] GLR outputs match (mostly) Dennett outputs, when distance in km is used

Variable --------------	Coefficients	Standard error	t-Statistic	Probability
vi1_origpop_log -------	0.5898	0.0009	638.5613	0
wj3_destmedinc_log ----	-0.158	0.0034	-46.9012	0
NEAR_DIST_log	--------- -0.8112	0.001	-799.0692	0
Intercept	------------- 7.1408	0.0249	286.975	0
AIC ------------------- 1505064.5035

[*] Apply coefficients to Equation 6

math.exp(7.1408+(0.5898*!vi1_origpop_log!)+(-0.158*!wj3_destmedinc_log!)-(abs(0.8112)*!NEAR_DIST_log!))

There is no need for additional scaling, as we are using our `k` parameter here

[*] Evaluate

R2  (calculated correctly and "incorrectly" via the graph), matches Dennett (0.32)

### Production Constrained Model

[*] Encode Field, using ORIG_GSCA_CODE

[*] GLR, adding all BUT ONE of the dummy variables

This produces: 

Variable	---------------------- Coefficients	Standard error	t-Statistic	Probability
wj3_destmedinc_log -------------	-0.2621	0.0034	-77.4767	0
NEAR_DIST_log ------------------	-1.2329	0.0014	-878.3314	0
ONEHOT_ORIG_GCCSA_CODE_1RNSW ---	0.118	0.0033	-35.9497	0
ONEHOT_ORIG_GCCSA_CODE_2GMEL ---	-0.6878	0.0035	-198.8814	0
ONEHOT_ORIG_GCCSA_CODE_2RVIC ---	-1.2255	0.0041	-300.6798	0
ONEHOT_ORIG_GCCSA_CODE_3GBRI ---	0.3158	0.0035	89.3466	0
ONEHOT_ORIG_GCCSA_CODE_3RQLD ---	0.5512	0.0035	155.3897	0
ONEHOT_ORIG_GCCSA_CODE_4GADE ---	-0.7982	0.0044	-180.0874	0
ONEHOT_ORIG_GCCSA_CODE_4RSAU ---	-1.2201	0.0058	-208.9381	0
ONEHOT_ORIG_GCCSA_CODE_5GPER ---	0.4689	0.0044	106.4538	0
ONEHOT_ORIG_GCCSA_CODE_5RWAU ---	-0.1414	0.0049	-28.7092	0
ONEHOT_ORIG_GCCSA_CODE_6GHOB ---	-2.7411	0.0081	-338.6711	0
ONEHOT_ORIG_GCCSA_CODE_6RTAS ---	-2.533	0.0071	-357.3425	0
ONEHOT_ORIG_GCCSA_CODE_7GDAR ---	-0.9287	0.007	-132.4044	0
ONEHOT_ORIG_GCCSA_CODE_7RNTE ---	-1.7377	0.0088	-198.1552	0
ONEHOT_ORIG_GCCSA_CODE_8ACTE ---	-1.7514	0.0054	-325.001	0
Intercept	---------------------- 19.5166	0.0238	821.2961	0

[*] Apply to Equation 6

# 
math.exp(19.5166+
(!ONEHOT_ORIG_GCCSA_CODE_1RNSW!*0.118)+
(!ONEHOT_ORIG_GCCSA_CODE_2GMEL!*-0.6878)+
(!ONEHOT_ORIG_GCCSA_CODE_2RVIC!*-1.2255)+	
(!ONEHOT_ORIG_GCCSA_CODE_3GBRI!*0.3158)+	
(!ONEHOT_ORIG_GCCSA_CODE_3RQLD!*0.5512)+	
(!ONEHOT_ORIG_GCCSA_CODE_4GADE!*-0.7982)+	
(!ONEHOT_ORIG_GCCSA_CODE_4RSAU!*-1.2201)+	
(!ONEHOT_ORIG_GCCSA_CODE_5GPER!*0.4689)+
(!ONEHOT_ORIG_GCCSA_CODE_5RWAU!*-0.1414)+	
(!ONEHOT_ORIG_GCCSA_CODE_6GHOB!*-2.7411)+	
(!ONEHOT_ORIG_GCCSA_CODE_6RTAS!*-2.533)+	
(!ONEHOT_ORIG_GCCSA_CODE_7GDAR!*-0.9287)+	
(!ONEHOT_ORIG_GCCSA_CODE_7RNTE!*-1.7377)+	
(!ONEHOT_ORIG_GCCSA_CODE_8ACTE!*-1.7514)+	
(-0.2621*!wj3_destmedinc_log!)-(abs(-1.2329)*!NEAR_DIST_log!))

# Correct formatting
math.exp(19.5166+(!ONEHOT_ORIG_GCCSA_CODE_1RNSW!*0.118)+(!ONEHOT_ORIG_GCCSA_CODE_2GMEL!*-0.6878)+
(!ONEHOT_ORIG_GCCSA_CODE_2RVIC!*-1.2255)+(!ONEHOT_ORIG_GCCSA_CODE_3GBRI!*0.3158)+(!ONEHOT_ORIG_GCCSA_CODE_3RQLD!*0.5512)+(!ONEHOT_ORIG_GCCSA_CODE_4GADE!*-0.7982)+    
(!ONEHOT_ORIG_GCCSA_CODE_4RSAU!*-1.2201)+(!ONEHOT_ORIG_GCCSA_CODE_5GPER!*0.4689)+(!ONEHOT_ORIG_GCCSA_CODE_5RWAU!*-0.1414)+(!ONEHOT_ORIG_GCCSA_CODE_6GHOB!*-2.7411)+(!ONEHOT_ORIG_GCCSA_CODE_6RTAS!*-2.533)+(!ONEHOT_ORIG_GCCSA_CODE_7GDAR!*-0.9287)+(!ONEHOT_ORIG_GCCSA_CODE_7RNTE!*-1.7377)+(!ONEHOT_ORIG_GCCSA_CODE_8ACTE!*-1.7514)+    
(-0.2621*!wj3_destmedinc_log!)-(abs(-1.2329)*!NEAR_DIST_log!))

[*] Evaluate

Measured-modelled R2 = 0.43 (matches Dennett), but the correct R2 for the origin-constrained model is similar to the total constrained (0.30)

================================================

### Simple unconstrained gravity model, using distance alone

Function: (Distance / 1000) ^ beta, where beta = -0.8

[*] Calculate Field `gm1`
  -> pow(!NEAR_DIST! / 1000, -0.8)
  -> Float
  
[*] Let's visualise this result for a single country desination, Select by Attributes (United Kingdom), XY to Line (Geodesic, Preserve Attributes), Size by `gm1`.

[*] Problems?
  -> For a start, these values are dimensionless (flow estimates with no units) - they don't translate into # people moving
  -> More importantly, we are only incorporating distance here, based on an inverse power distance decay function i.e., as distance increases, flow decreases
  -> We know this is unlikely to capture flow of people, which is governed by lots of other factors e.g., population size, GDP, cultural similarity, cost of movement, plus other factors e.g., conflict, climate, political reasons.
  -> To improve our SIM, we want to include the **mass** of the origin and destinations 

### Scaling

\(k\): A scaling constant used to calibrate the model to real-world data

[*] Calculate scale factor (Explore Statistics) = sum of measured flows (`flow_2024`, 277,172,84) / sum of modelled flows (`gm1`, 76.04158422681869) = 364,501.6642121002

[*] Apply scale factor (`gm1_scaled`)

... doesn't produce much! 

[*] Simple gravity model: !ORIG_POP! times !DEST_POP! / pow(!NEAR_DIST!, 2) ... Field Type = Double

[*] Including GDP: (!ORIG_POP! times !DEST_POP!) times (!ORIG_GDP! times  !DEST_GDP!) / pow(!NEAR_DIST!, 2)

==========================================================

#### Natural Earth attempt

[1] Load Natural Earth data 

[2] Return Centroids (Feature to Point) ... discuss: sensitivity to feature geometry

[3] Generate Near Table (links based on ID), using geodesic measurement, [!] save in Geodatabase (editable)

  [*] Calculate Centroid (Add Geometry), if not present... 

[4] Join Field, keeping the origin information (IN_FID), using 'Use Field Mapping' to select attributes of interest and updating names:
  - orig_ISO_A3_EH [ISO_A3_EH] see [explanation](https://bookdown.org/pbaumgartner/gdswr-notes-new/91-creating-maps.html#plotting-a-world-map)
  - orig_name [NAME]
  - orig_gdp [Gross Domestic Product in millions of US Dollars ( Millions $ )]
  - orig_pop
  - orig_X, orig_Y
  
[5] Repeat, for destinations (NEAR_FID)
  - dest_ISO_A3_EH [ISO_A3_EH]
  - dest_name
  - dest_gdp
  - dest_pop
  - dest_X, dest_Y
  
  [-] Export to Geodatabase (editable)

[6] Create Origin-Destination field in the near table
  - !ORIG_ISO_A3_EH! + "-" + !DEST_ISO_A3_EH!
  
[7] GDP per capita more useful, influencing your decision to move... Add Field:

  `ORIG_GDP_CAP` = (!ORIG_GDP! * 1000000) / !ORIG_POP!
  `DEST_GDP_CAP` = (!DEST_GDP! * 1000000) / !DEST_POP!

[8] Load world-international-migrant-stocks and inspect

[9] Join to Abel and Cohen (2019) data, using origin-destination, transferring:
  -> flow (2015-2020 movement of people)
  -> [NOT] contig (share a border), as it's rubbish! 
  -> common_lang (share a common language)
  -> continent-descriptor (summarise inter- or intra-continent movement)
  
  [!] this might take a while!, 52_000 rows, ~5 mins for 31%, ~9 mins total
  
  ''' Original approach, using UN data
  [*] Then Join Field based on Origin-Destination, transfer fields = Stock_2020, Stock_2024
    - Note, not all pairs will have data!
    
  [*] Calculate flow of migrants (2020-2024) using Add Field (`flow_2024`)
    - NULL for missing bilateral flows
  '''
  
[10] Remove rows where GDP / population are 0 or less, Select by Attributes (ORIG_POP = 0 Or DEST_POP = 0)

  [!] Vatican has a GDP of -99, remove GDP < 0
  
  [!] Remove flow `is null`

[11] Bordering nation?

  -> The data from Reina et al. (2024) is poor i.e., Andorra has no contiguous borders, Spain is contiguous with Faroe Islands
  -> We can do better...
  -> Load the Spatial Weights matrix table produced in Week 2 (Contains NE_IDs)
  -> Join Fields (NE_ID)
    = orig_ISO_A3_EH
  -> Join Field (NID)
    = dest_ISO_A3_EH
  -> Create origin-destination field
  -> Create binary bordering field (`contig` = 1)
  -> Join Field based on origin-destination, linking contig
  -> This produces 1 (bordering) or <Null> (not bordering)
  -> Calculate Field, update `contig` using: 0 if !contig! is None else !contig!

[12] Let's visualise some of the flow data
  - Select by Attributes i.e., flow > 20_000 (n=~800) or 100_000 (n=~200)
  - XY to Line 
  - Size by Flow_2024
  [REMOVE] as a complex dataset
  
    -> Contiguity (binary, `contig`) ... produced manually based on SWM
  -> Common language (binary, `common_lang`)

Absent:
  -> origin-destination unemployment rates or % in rented accomodation 
  -> 'FlowNoIntra' i.e., intra-zonal flows (which are removed anyway)
  
Try Africa to Europe ... 

Interesting relationships:
- origin_gdp_cap (no money no travel, lots of money no need, goldilocks)
- dest_gdp_cap - similar, extremely high GDP destinations are small (e.g., Monaco)
- contig (Morocco only)
- NEAR_DIST - biggest flows to Spain, France and Italy
- some language link... mean flow for common language (3048.42), no common language (521.0321691176471)

==========================================================

## Data Processing

Abel and Cohen (2019) data
-> https://www.nature.com/articles/s41597-019-0089-3
-> https://figshare.com/collections/Bilateral_international_migration_flow_estimates_for_200_countries/4470464

Caballero Reina et al. (2024)
-> https://doi.org/10.1007/s11113-024-09867-6
-> https://github.com/jakobZellmann/Gravity-Models-for-Global-Migration-Flows-A-Predictive-Evaluation 

### Abel and Cohen data

Abel, G.J., Cohen, J.E. Bilateral international migration flow estimates for 200 countries. Sci Data 6, 82 (2019). https://doi.org/10.1038/s41597-019-0089-3

[1] Focused on earlier data, not subset by sex (simpler)
[2] Filtered to 2015-2020 only and removed 'year_0' column 
[3] Added full country names based on provided list
[4] Removed duplicates (i.e., Burundi-Burundi)
[5] Added origin-destination column, and removed separated columns.
[6] Focused on `da_pb_closed` only (pseudo-Bayesian method) and renamed to 'flow'
[7] Changed country names:
  -> DR Congo = Democratic Republic of the Congo
  -> Hong Kong SAR = Hong Kong S.A.R
  -> Macao SAR = Macao S.A.R
  -> Timor-Leste = East Timor
  
### UN Data

Source: https://www.un.org/development/desa/pd/content/international-migrant-stock 

[! PROBLEM !] Stock data can't be used simply to generate flows, as many different flow patterns could generate the net stock changes...
See: https://www.migrationdataportal.org/themes/international-migration-flows

[1] Filtered to national origin locations (location code of origin < 900)
[2] Reduced to national level destinations (Location code of destination < 900)
[3] Removed index, Coverage, Data type
[4] Simplified headings and saved as csv
[5] Removed astrixes [Find and Replace, ~*]
[6] Changed country names:
  -> Bolivia (Plurinational State of) = Bolivia
  -> China, Hong Kong SAR = Hong Kong
  -> Iran (Islamic Republic of) = Iran
  -> Dem. People's Republic of Korea = North Korea
  -> Republic of Korea = South Korea
  -> Lao People's Democratic Republic = Laos
  -> Republic of Moldova = Moldova
  -> Russian Federation = Russia
  -> Türkiye = Turkey
  -> Venezuela (Bolivarian Republic of) = Venezuela
  -> China, Taiwan Province of China = Taiwan
[7] Created Origin-Destination attribute
[8] Created "" in the near table

[9] Log 2024 stock, and origin-destination GDPs and populations
[10] Regression, R2=0.902179456, SE=0.974522251, n=7986
  Coefficients
  Intercept	0
  log(dist)	-0.861337546
  log(o_pop)	0.546597538
  log(o_gdp)	0.049761413
  log(d_pop)	0.250452024
  log(d_gdp)	0.531296542

### World Bank data

Source: https://databank.worldbank.org/source/global-bilateral-migration# 

Described [here](https://www.migrationdataportal.org/themes/international-migration-flows) as "flow", but self-describes as "stock" (see above)
